require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RubyGemsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RubyGem. As you add validations to RubyGem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RubyGemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ruby_gems as @ruby_gems" do
      ruby_gem = RubyGem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ruby_gems)).to eq([ruby_gem])
    end
  end

  describe "GET #show" do
    it "assigns the requested ruby_gem as @ruby_gem" do
      ruby_gem = RubyGem.create! valid_attributes
      get :show, {:id => ruby_gem.to_param}, valid_session
      expect(assigns(:ruby_gem)).to eq(ruby_gem)
    end
  end

  describe "GET #new" do
    it "assigns a new ruby_gem as @ruby_gem" do
      get :new, {}, valid_session
      expect(assigns(:ruby_gem)).to be_a_new(RubyGem)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ruby_gem as @ruby_gem" do
      ruby_gem = RubyGem.create! valid_attributes
      get :edit, {:id => ruby_gem.to_param}, valid_session
      expect(assigns(:ruby_gem)).to eq(ruby_gem)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RubyGem" do
        expect {
          post :create, {:ruby_gem => valid_attributes}, valid_session
        }.to change(RubyGem, :count).by(1)
      end

      it "assigns a newly created ruby_gem as @ruby_gem" do
        post :create, {:ruby_gem => valid_attributes}, valid_session
        expect(assigns(:ruby_gem)).to be_a(RubyGem)
        expect(assigns(:ruby_gem)).to be_persisted
      end

      it "redirects to the created ruby_gem" do
        post :create, {:ruby_gem => valid_attributes}, valid_session
        expect(response).to redirect_to(RubyGem.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ruby_gem as @ruby_gem" do
        post :create, {:ruby_gem => invalid_attributes}, valid_session
        expect(assigns(:ruby_gem)).to be_a_new(RubyGem)
      end

      it "re-renders the 'new' template" do
        post :create, {:ruby_gem => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ruby_gem" do
        ruby_gem = RubyGem.create! valid_attributes
        put :update, {:id => ruby_gem.to_param, :ruby_gem => new_attributes}, valid_session
        ruby_gem.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ruby_gem as @ruby_gem" do
        ruby_gem = RubyGem.create! valid_attributes
        put :update, {:id => ruby_gem.to_param, :ruby_gem => valid_attributes}, valid_session
        expect(assigns(:ruby_gem)).to eq(ruby_gem)
      end

      it "redirects to the ruby_gem" do
        ruby_gem = RubyGem.create! valid_attributes
        put :update, {:id => ruby_gem.to_param, :ruby_gem => valid_attributes}, valid_session
        expect(response).to redirect_to(ruby_gem)
      end
    end

    context "with invalid params" do
      it "assigns the ruby_gem as @ruby_gem" do
        ruby_gem = RubyGem.create! valid_attributes
        put :update, {:id => ruby_gem.to_param, :ruby_gem => invalid_attributes}, valid_session
        expect(assigns(:ruby_gem)).to eq(ruby_gem)
      end

      it "re-renders the 'edit' template" do
        ruby_gem = RubyGem.create! valid_attributes
        put :update, {:id => ruby_gem.to_param, :ruby_gem => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ruby_gem" do
      ruby_gem = RubyGem.create! valid_attributes
      expect {
        delete :destroy, {:id => ruby_gem.to_param}, valid_session
      }.to change(RubyGem, :count).by(-1)
    end

    it "redirects to the ruby_gems list" do
      ruby_gem = RubyGem.create! valid_attributes
      delete :destroy, {:id => ruby_gem.to_param}, valid_session
      expect(response).to redirect_to(ruby_gems_url)
    end
  end

end
